import type {
  Mandapam,
  MandapamPackage,
  Booking,
  Review,
  Vendor,
  TimeSlot,
  StaffMember,
  Dispute,
  FAQ,
  KPICard,
} from "./types";

// ===== Mandapams =====
export const mandapams: Mandapam[] = [
  {
    id: "m1",
    vendorId: "v1",
    vendorName: "Sri Lakshmi Events",
    name: "Sri Lakshmi Grand Mandapam",
    slug: "sri-lakshmi-grand-mandapam",
    description:
      "A premium wedding venue in the heart of Hyderabad featuring luxurious interiors, spacious halls, and world-class amenities. Perfect for grand Telugu weddings with traditional touch.",
    shortDescription: "Premium wedding hall with AC, catering & decor",
    images: [
      "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&q=80",
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&q=80",
      "https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=800&q=80",
      "https://images.unsplash.com/photo-1478146059778-26028b07395a?w=800&q=80",
    ],
    city: "Hyderabad",
    area: "Jubilee Hills",
    state: "Telangana",
    address: "Plot 42, Road No. 10, Jubilee Hills, Hyderabad",
    capacity: 1000,
    parkingSlots: 200,
    rooms: 10,
    hasCatering: true,
    hasAC: true,
    hasDecoration: true,
    hasDJ: true,
    hasPhotography: true,
    rating: 4.8,
    reviewCount: 124,
    pricePerDay: 250000,
    pricePerSlot: 150000,
    status: "APPROVED",
    amenities: [
      "Central AC",
      "Valet Parking",
      "Bridal Suite",
      "In-house Catering",
      "Stage Decoration",
      "DJ & Sound",
      "Photography",
      "Generator Backup",
      "CCTV Surveillance",
      "Lift Access",
    ],
    policies: {
      cancellation: "Free cancellation up to 30 days before event. 50% refund within 15-30 days.",
      refund: "Refunds processed within 7-10 business days to original payment method.",
      timing: "Morning: 6AM-2PM, Evening: 4PM-12AM, Full Day: 6AM-12AM",
    },
    createdAt: "2024-06-15",
  },
  {
    id: "m2",
    vendorId: "v2",
    vendorName: "Rajam Kalyana Mandapam",
    name: "Rajam Royal Convention",
    slug: "rajam-royal-convention",
    description:
      "An elegant convention center in Vijayawada with modern facilities and traditional charm. Ideal for both intimate and grand celebrations.",
    shortDescription: "Elegant hall with 500+ capacity in Vijayawada",
    images: [
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&q=80",
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
      "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?w=800&q=80",
    ],
    city: "Vijayawada",
    area: "Benz Circle",
    state: "Andhra Pradesh",
    address: "Benz Circle, MG Road, Vijayawada",
    capacity: 500,
    parkingSlots: 100,
    rooms: 5,
    hasCatering: true,
    hasAC: true,
    hasDecoration: false,
    hasDJ: false,
    hasPhotography: false,
    rating: 4.5,
    reviewCount: 89,
    pricePerDay: 120000,
    pricePerSlot: 75000,
    status: "APPROVED",
    amenities: [
      "Central AC",
      "Parking",
      "In-house Catering",
      "Generator Backup",
      "CCTV",
      "Wi-Fi",
    ],
    policies: {
      cancellation: "Free cancellation up to 15 days before event.",
      refund: "Refunds within 10 business days.",
      timing: "Morning: 7AM-1PM, Evening: 5PM-11PM, Full Day: 7AM-11PM",
    },
    createdAt: "2024-08-22",
  },
  {
    id: "m3",
    vendorId: "v1",
    vendorName: "Sri Lakshmi Events",
    name: "Lakshmi Garden Mandapam",
    slug: "lakshmi-garden-mandapam",
    description:
      "Beautiful open-air garden venue surrounded by lush greenery. Perfect for outdoor ceremonies, sangeet nights, and reception parties.",
    shortDescription: "Open-air garden venue for outdoor weddings",
    images: [
      "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&q=80",
      "https://images.unsplash.com/photo-1510076857177-7470076d4098?w=800&q=80",
    ],
    city: "Hyderabad",
    area: "Gachibowli",
    state: "Telangana",
    address: "Gachibowli, Near DLF, Hyderabad",
    capacity: 800,
    parkingSlots: 150,
    rooms: 4,
    hasCatering: true,
    hasAC: false,
    hasDecoration: true,
    hasDJ: true,
    hasPhotography: true,
    rating: 4.6,
    reviewCount: 67,
    pricePerDay: 180000,
    pricePerSlot: 100000,
    status: "APPROVED",
    amenities: [
      "Garden Setting",
      "Outdoor Stage",
      "Catering",
      "Decoration",
      "DJ & Lighting",
      "Photography",
      "Parking",
      "Restrooms",
    ],
    policies: {
      cancellation: "Free cancellation up to 20 days before event.",
      refund: "Refunds within 7 business days.",
      timing: "Morning: 6AM-2PM, Evening: 4PM-11PM, Full Day: 6AM-11PM",
    },
    createdAt: "2024-09-10",
  },
  {
    id: "m4",
    vendorId: "v3",
    vendorName: "Sai Baba Kalyana Mandapam",
    name: "Sai Baba Convention Centre",
    slug: "sai-baba-convention-centre",
    description:
      "Affordable and spacious convention centre in Tirupati. Close to the temple with easy access for pilgrims and wedding guests alike.",
    shortDescription: "Affordable hall near Tirupati temple",
    images: [
      "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=800&q=80",
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80",
    ],
    city: "Tirupati",
    area: "Alipiri Road",
    state: "Andhra Pradesh",
    address: "Alipiri Road, Near Temple, Tirupati",
    capacity: 600,
    parkingSlots: 80,
    rooms: 6,
    hasCatering: true,
    hasAC: true,
    hasDecoration: false,
    hasDJ: false,
    hasPhotography: false,
    rating: 4.3,
    reviewCount: 45,
    pricePerDay: 80000,
    pricePerSlot: 50000,
    status: "APPROVED",
    amenities: ["AC", "Parking", "Catering", "Generator", "Temple Proximity"],
    policies: {
      cancellation: "50% refund up to 10 days before event.",
      refund: "Refunds within 14 business days.",
      timing: "Morning: 5AM-1PM, Evening: 4PM-11PM",
    },
    createdAt: "2024-07-05",
  },
  {
    id: "m5",
    vendorId: "v4",
    vendorName: "Annapurna Conventions",
    name: "Annapurna Grand Hall",
    slug: "annapurna-grand-hall",
    description:
      "State-of-the-art convention hall in Vizag with ocean views. Luxurious interiors, professional event management, and premium catering services.",
    shortDescription: "Luxury hall with ocean views in Vizag",
    images: [
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80",
      "https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800&q=80",
    ],
    city: "Visakhapatnam",
    area: "Beach Road",
    state: "Andhra Pradesh",
    address: "Beach Road, RK Beach, Visakhapatnam",
    capacity: 1200,
    parkingSlots: 250,
    rooms: 12,
    hasCatering: true,
    hasAC: true,
    hasDecoration: true,
    hasDJ: true,
    hasPhotography: true,
    rating: 4.9,
    reviewCount: 156,
    pricePerDay: 350000,
    pricePerSlot: 200000,
    status: "APPROVED",
    amenities: [
      "Ocean View",
      "Central AC",
      "Valet Parking",
      "Bridal Suite",
      "Catering",
      "Decoration",
      "DJ",
      "Photography",
      "Swimming Pool",
      "Spa",
      "Helipad",
    ],
    policies: {
      cancellation: "Free cancellation up to 45 days before event.",
      refund: "Full refund within 5 business days.",
      timing: "Flexible timing available. Contact for details.",
    },
    createdAt: "2024-05-20",
  },
  {
    id: "m6",
    vendorId: "v2",
    vendorName: "Rajam Kalyana Mandapam",
    name: "Rajam Heritage Hall",
    slug: "rajam-heritage-hall",
    description:
      "Traditional heritage-style mandapam with intricate wood carvings, brass details, and authentic South Indian architecture.",
    shortDescription: "Heritage-style traditional mandapam",
    images: [
      "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=800&q=80",
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&q=80",
    ],
    city: "Vijayawada",
    area: "Eluru Road",
    state: "Andhra Pradesh",
    address: "Eluru Road, Near Bus Stand, Vijayawada",
    capacity: 350,
    parkingSlots: 60,
    rooms: 3,
    hasCatering: true,
    hasAC: true,
    hasDecoration: true,
    hasDJ: false,
    hasPhotography: false,
    rating: 4.4,
    reviewCount: 38,
    pricePerDay: 95000,
    pricePerSlot: 55000,
    status: "APPROVED",
    amenities: [
      "Heritage Architecture",
      "AC",
      "Parking",
      "Catering",
      "Traditional Decor",
      "Generator",
    ],
    policies: {
      cancellation: "Non-refundable within 7 days of event.",
      refund: "Refund within 10 business days.",
      timing: "Morning: 6AM-1PM, Evening: 5PM-11PM",
    },
    createdAt: "2024-10-01",
  },
];

// ===== Packages =====
export const packages: MandapamPackage[] = [
  {
    id: "pkg1",
    mandapamId: "m1",
    name: "Silver Package",
    description: "Basic hall rental with seating arrangement and basic decoration",
    price: 150000,
    inclusions: ["Hall Rental", "Basic Seating (500)", "Basic Decoration", "Sound System", "Generator Backup"],
    isPopular: false,
  },
  {
    id: "pkg2",
    mandapamId: "m1",
    name: "Gold Package",
    description: "Complete wedding package with catering, decoration, and photography",
    price: 350000,
    inclusions: [
      "Hall Rental",
      "Premium Seating (800)",
      "Premium Decoration",
      "Catering (Veg + Non-Veg)",
      "Photography",
      "Sound & DJ",
      "Bridal Room",
      "Generator Backup",
    ],
    isPopular: true,
  },
  {
    id: "pkg3",
    mandapamId: "m1",
    name: "Platinum Package",
    description: "All-inclusive luxury package for a grand celebration",
    price: 600000,
    inclusions: [
      "Hall Rental",
      "Royal Seating (1000)",
      "Luxury Decoration",
      "Premium Catering",
      "Photo + Video",
      "DJ + Live Band",
      "Bridal Suite",
      "Valet Parking",
      "Welcome Drinks",
      "Return Gifts",
    ],
    isPopular: false,
  },
];

// ===== Vendors =====
export const vendors: Vendor[] = [
  {
    id: "v1",
    userId: "u1",
    businessName: "Sri Lakshmi Events",
    businessEmail: "contact@srilakshmi.com",
    businessPhone: "+91 9876543210",
    description: "Premier wedding event management with 15+ years of experience in Hyderabad.",
    city: "Hyderabad",
    state: "Telangana",
    status: "APPROVED",
    rating: 4.7,
    reviewCount: 191,
    totalBookings: 450,
    joinedAt: "2023-01-15",
  },
  {
    id: "v2",
    userId: "u2",
    businessName: "Rajam Kalyana Mandapam",
    businessEmail: "info@rajamevents.com",
    businessPhone: "+91 9876543211",
    description: "Traditional and modern wedding venues in Vijayawada since 2010.",
    city: "Vijayawada",
    state: "Andhra Pradesh",
    status: "APPROVED",
    rating: 4.5,
    reviewCount: 127,
    totalBookings: 320,
    joinedAt: "2023-03-20",
  },
  {
    id: "v3",
    userId: "u3",
    businessName: "Sai Baba Kalyana Mandapam",
    businessEmail: "saibaba@mandapam.com",
    businessPhone: "+91 9876543212",
    description: "Affordable wedding halls near Tirupati temple.",
    city: "Tirupati",
    state: "Andhra Pradesh",
    status: "APPROVED",
    rating: 4.3,
    reviewCount: 45,
    totalBookings: 180,
    joinedAt: "2023-06-10",
  },
  {
    id: "v4",
    userId: "u4",
    businessName: "Annapurna Conventions",
    businessEmail: "hello@annapurna.com",
    businessPhone: "+91 9876543213",
    description: "Luxury convention halls with ocean views in Visakhapatnam.",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    status: "APPROVED",
    rating: 4.9,
    reviewCount: 156,
    totalBookings: 520,
    joinedAt: "2022-11-01",
  },
];

// ===== Bookings =====
export const bookings: Booking[] = [
  {
    id: "b1",
    userId: "u5",
    userName: "Ramesh Kumar",
    userPhone: "+91 9876500001",
    mandapamId: "m1",
    mandapamName: "Sri Lakshmi Grand Mandapam",
    mandapamImage: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=400&q=80",
    vendorId: "v1",
    vendorName: "Sri Lakshmi Events",
    packageId: "pkg2",
    packageName: "Gold Package",
    date: "2026-03-15",
    slot: "FULL_DAY",
    slotLabel: "Full Day (6AM - 12AM)",
    guests: 500,
    status: "CONFIRMED",
    totalAmount: 413000,
    advancePaid: 100000,
    balanceDue: 313000,
    tax: 63000,
    createdAt: "2026-01-10",
    updatedAt: "2026-01-12",
    timeline: [
      { id: "t1", status: "CREATED", message: "Booking request submitted", timestamp: "2026-01-10T10:30:00" },
      { id: "t2", status: "ADVANCE_PAID", message: "Advance payment of 1,00,000 received", timestamp: "2026-01-10T10:35:00" },
      { id: "t3", status: "CONFIRMED", message: "Booking confirmed by vendor", timestamp: "2026-01-12T14:00:00" },
    ],
  },
  {
    id: "b2",
    userId: "u6",
    userName: "Priya Reddy",
    userPhone: "+91 9876500002",
    mandapamId: "m5",
    mandapamName: "Annapurna Grand Hall",
    mandapamImage: "https://images.unsplash.com/photo-1519741497674-611481863552?w=400&q=80",
    vendorId: "v4",
    vendorName: "Annapurna Conventions",
    packageId: "pkg3",
    packageName: "Platinum Package",
    date: "2026-04-20",
    slot: "FULL_DAY",
    slotLabel: "Full Day",
    guests: 800,
    status: "PENDING",
    totalAmount: 708000,
    advancePaid: 0,
    balanceDue: 708000,
    tax: 108000,
    createdAt: "2026-02-01",
    updatedAt: "2026-02-01",
    timeline: [
      { id: "t4", status: "CREATED", message: "Booking request submitted", timestamp: "2026-02-01T09:00:00" },
    ],
  },
  {
    id: "b3",
    userId: "u7",
    userName: "Suresh Babu",
    userPhone: "+91 9876500003",
    mandapamId: "m2",
    mandapamName: "Rajam Royal Convention",
    mandapamImage: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=400&q=80",
    vendorId: "v2",
    vendorName: "Rajam Kalyana Mandapam",
    date: "2026-02-28",
    slot: "MORNING",
    slotLabel: "Morning (7AM - 1PM)",
    guests: 300,
    status: "COMPLETED",
    totalAmount: 88500,
    advancePaid: 88500,
    balanceDue: 0,
    tax: 13500,
    createdAt: "2026-01-05",
    updatedAt: "2026-02-28",
    timeline: [
      { id: "t5", status: "CREATED", message: "Booking request submitted", timestamp: "2026-01-05T11:00:00" },
      { id: "t6", status: "CONFIRMED", message: "Booking confirmed", timestamp: "2026-01-06T09:00:00" },
      { id: "t7", status: "COMPLETED", message: "Event completed successfully", timestamp: "2026-02-28T14:00:00" },
    ],
  },
  {
    id: "b4",
    userId: "u8",
    userName: "Lakshmi Devi",
    userPhone: "+91 9876500004",
    mandapamId: "m4",
    mandapamName: "Sai Baba Convention Centre",
    mandapamImage: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=400&q=80",
    vendorId: "v3",
    vendorName: "Sai Baba Kalyana Mandapam",
    date: "2026-03-10",
    slot: "EVENING",
    slotLabel: "Evening (4PM - 11PM)",
    guests: 400,
    status: "CANCELLED",
    totalAmount: 59000,
    advancePaid: 25000,
    balanceDue: 0,
    tax: 9000,
    createdAt: "2026-01-20",
    updatedAt: "2026-02-05",
    timeline: [
      { id: "t8", status: "CREATED", message: "Booking request submitted", timestamp: "2026-01-20T15:00:00" },
      { id: "t9", status: "CONFIRMED", message: "Booking confirmed", timestamp: "2026-01-21T10:00:00" },
      { id: "t10", status: "CANCELLED", message: "Cancelled by customer", timestamp: "2026-02-05T12:00:00" },
    ],
  },
];

// ===== Reviews =====
export const reviews: Review[] = [
  {
    id: "r1",
    userId: "u5",
    userName: "Ramesh Kumar",
    mandapamId: "m1",
    rating: 5,
    comment: "Absolutely wonderful venue! The decoration and catering were top-notch. Our wedding was perfect.",
    createdAt: "2025-12-20",
  },
  {
    id: "r2",
    userId: "u7",
    userName: "Suresh Babu",
    mandapamId: "m1",
    rating: 4,
    comment: "Great hall with spacious interiors. Parking could be better managed during peak hours.",
    createdAt: "2025-11-15",
  },
  {
    id: "r3",
    userId: "u8",
    userName: "Lakshmi Devi",
    userAvatar: undefined,
    mandapamId: "m1",
    rating: 5,
    comment: "Beautiful mandapam with excellent staff. They took care of every detail. Highly recommended!",
    createdAt: "2025-10-08",
  },
  {
    id: "r4",
    userId: "u6",
    userName: "Priya Reddy",
    mandapamId: "m2",
    rating: 4,
    comment: "Good venue for mid-size weddings. Clean, well-maintained, and affordable.",
    createdAt: "2025-09-22",
  },
];

// ===== Time Slots =====
export const timeSlots: TimeSlot[] = [
  { id: "ts1", type: "MORNING", label: "Morning Slot", startTime: "6:00 AM", endTime: "2:00 PM", available: true, price: 150000 },
  { id: "ts2", type: "EVENING", label: "Evening Slot", startTime: "4:00 PM", endTime: "12:00 AM", available: true, price: 180000 },
  { id: "ts3", type: "FULL_DAY", label: "Full Day", startTime: "6:00 AM", endTime: "12:00 AM", available: false, price: 250000 },
];

// ===== Staff =====
export const staffMembers: StaffMember[] = [
  {
    id: "s1",
    vendorId: "v1",
    name: "Arun Kumar",
    email: "arun@srilakshmi.com",
    role: "Manager",
    permissions: ["bookings.view", "bookings.manage", "mandapams.view", "mandapams.edit"],
    addedAt: "2024-01-15",
  },
  {
    id: "s2",
    vendorId: "v1",
    name: "Sneha Reddy",
    email: "sneha@srilakshmi.com",
    role: "Receptionist",
    permissions: ["bookings.view", "mandapams.view"],
    addedAt: "2024-03-20",
  },
  {
    id: "s3",
    vendorId: "v1",
    name: "Ravi Teja",
    email: "ravi@srilakshmi.com",
    role: "Accountant",
    permissions: ["bookings.view", "payments.view", "payments.manage"],
    addedAt: "2024-06-01",
  },
];

// ===== Disputes =====
export const disputes: Dispute[] = [
  {
    id: "d1",
    bookingId: "b4",
    userId: "u8",
    userName: "Lakshmi Devi",
    subject: "Refund not received for cancelled booking",
    description: "I cancelled my booking 35 days before the event but haven't received my refund yet.",
    status: "OPEN",
    createdAt: "2026-02-10",
  },
  {
    id: "d2",
    bookingId: "b3",
    userId: "u7",
    userName: "Suresh Babu",
    subject: "AC was not working during event",
    description: "The AC in the main hall stopped working 2 hours into our ceremony. We need partial refund.",
    status: "IN_PROGRESS",
    createdAt: "2026-03-01",
  },
];

// ===== FAQs =====
export const faqs: FAQ[] = [
  {
    question: "How do I book a mandapam?",
    answer:
      "Search for mandapams by city, date, and capacity. Select your preferred venue, choose a package and time slot, then proceed with advance payment to confirm your booking.",
  },
  {
    question: "What is the cancellation policy?",
    answer:
      "Each mandapam has its own cancellation policy. Generally, free cancellation is available 15-30 days before the event. Check the specific venue's policies for details.",
  },
  {
    question: "How much advance do I need to pay?",
    answer:
      "Typically, a 25-50% advance is required to confirm your booking. The remaining balance can be paid before or on the day of the event.",
  },
  {
    question: "Can I visit the mandapam before booking?",
    answer:
      "Yes! You can contact the vendor directly through the platform to schedule a visit. Most vendors offer free site visits.",
  },
  {
    question: "How do I become a vendor?",
    answer:
      "Click on 'List Your Venue' and fill out the registration form with your business details, documents, and venue information. Our team will review and approve your listing within 2-3 business days.",
  },
  {
    question: "What payment methods are accepted?",
    answer:
      "We accept UPI, net banking, debit/credit cards, and wallet payments. All transactions are secured with bank-grade encryption.",
  },
];

// ===== KPIs =====
export const vendorKPIs: KPICard[] = [
  {
    title: "Total Revenue",
    value: "₹24,50,000",
    change: 12.5,
    changeLabel: "vs last month",
    sparklineData: [18, 22, 19, 25, 28, 24, 30],
  },
  {
    title: "Active Bookings",
    value: "18",
    change: 8.3,
    changeLabel: "vs last month",
    sparklineData: [12, 14, 11, 16, 15, 17, 18],
  },
  {
    title: "Avg. Rating",
    value: "4.7",
    change: 2.1,
    changeLabel: "vs last month",
    sparklineData: [4.5, 4.6, 4.5, 4.7, 4.6, 4.7, 4.7],
  },
  {
    title: "Occupancy Rate",
    value: "78%",
    change: -3.2,
    changeLabel: "vs last month",
    sparklineData: [82, 80, 75, 78, 76, 79, 78],
  },
];

export const adminKPIs: KPICard[] = [
  {
    title: "Total Bookings",
    value: "1,247",
    change: 15.3,
    changeLabel: "vs last month",
    sparklineData: [980, 1020, 1050, 1100, 1150, 1200, 1247],
  },
  {
    title: "Platform Revenue",
    value: "₹1.2 Cr",
    change: 22.1,
    changeLabel: "vs last month",
    sparklineData: [80, 85, 90, 95, 100, 110, 120],
  },
  {
    title: "Active Vendors",
    value: "156",
    change: 5.8,
    changeLabel: "vs last month",
    sparklineData: [140, 142, 145, 148, 150, 153, 156],
  },
  {
    title: "Pending Approvals",
    value: "12",
    change: -18.0,
    changeLabel: "vs last week",
    sparklineData: [20, 18, 15, 14, 13, 12, 12],
  },
];

// ===== Revenue Chart Data =====
export const revenueChartData = [
  { month: "Aug", revenue: 1800000, bookings: 45 },
  { month: "Sep", revenue: 2200000, bookings: 52 },
  { month: "Oct", revenue: 2800000, bookings: 68 },
  { month: "Nov", revenue: 3500000, bookings: 85 },
  { month: "Dec", revenue: 4200000, bookings: 98 },
  { month: "Jan", revenue: 3800000, bookings: 88 },
  { month: "Feb", revenue: 2450000, bookings: 62 },
];

// ===== Cities =====
export const cities = [
  "Hyderabad",
  "Vijayawada",
  "Visakhapatnam",
  "Tirupati",
  "Guntur",
  "Warangal",
  "Rajahmundry",
  "Nellore",
  "Kurnool",
  "Kakinada",
];

// ===== Capacity Options =====
export const capacityOptions = [
  { label: "Up to 200", value: "200" },
  { label: "200 - 500", value: "500" },
  { label: "500 - 1000", value: "1000" },
  { label: "1000+", value: "1000+" },
];

// ===== Budget Ranges =====
export const budgetRanges = [
  { label: "Under ₹1 Lakh", min: 0, max: 100000 },
  { label: "₹1 - 2 Lakh", min: 100000, max: 200000 },
  { label: "₹2 - 5 Lakh", min: 200000, max: 500000 },
  { label: "₹5 Lakh+", min: 500000, max: Infinity },
];
